generate:
  lm_model: "gpt-4o-mini"
  output_length: 128
  num_of_examples: 144
  concept_path: "axbench/data/gemma-2-2b_10-gemmascope-res-16k.json"
  max_concepts: 500
  master_data_dir: "axbench/data"
  dataset_category: "instruction"
  lm_use_cache: false
  seed: 124
train:
  model_name: "google/gemma-2-2b-it"
  layer: 10
  component: "res"
  seed: 124
  use_bf16: true
  models:
    GemmaScopeSAEDiffMean:
      batch_size: 6
      n_epochs: 1
      binarize_dataset: true
      train_on_negative: false
      low_rank_dimension: 1
      intervention_type: "addition"
inference:
  use_bf16: true
  models: ["GemmaScopeSAEDiffMean"]
  model_name: "google/gemma-2-2b-it"
  output_length: 128
  latent_num_of_examples: 36
  latent_batch_size: 16
  steering_intervention_type: "addition"
  steering_model_name: "google/gemma-2-2b-it"
  steering_datasets: ["AlpacaEval"]
  steering_batch_size: 10
  steering_output_length: 128
  steering_layers: [10]
  steering_num_of_examples: 10
  steering_factors: [1.0, 2.0, 3.0, 3.5, 4.0, 5.0]
  master_data_dir: "axbench/data"
  seed: 124
  lm_model: "gpt-4o-mini"
  temperature: 1.0
evaluate:
  models: ["GemmaScopeSAEDiffMean"]
  latent_evaluators:
    - "AUCROCEvaluator"
    - "HardNegativeEvaluator"
  steering_evaluators:
    - "LMJudgeEvaluator"
  winrate_split_ratio: 0.5
  num_of_workers: 32
  lm_model: "gpt-4o-mini"
  run_winrate: false
  winrate_baseline: "PromptSteering"
  master_data_dir: "axbench/data"

